include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-docker/docker-build.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/custom-image.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/lulu/docker-deploy.yml'

stages:
  - pre-package
  - package
  - post-package
  - deploy

.deploy:
  variables:
    FORCE_DOCKER_COMPOSE: 1
    COMPOSE_FILE: compose.tts-api.yaml
    SERVICES_TO_CHECK: tts-api

.deploy-lulu:
  environment:
    name: lulu/tts-api

.deploy-caddy:
  variables: &deploy-caddy-variables
    FORCE_DOCKER_COMPOSE: 0
    COMPOSE_FILE: compose.caddy.yaml
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_caddy

.deploy-lulu-caddy:
  environment: &deploy-lulu-caddy-environment
    name: lulu/caddy

deploy-branch-lulu-caddy:
  extends: deploy-branch-lulu
  variables:
    <<: *deploy-caddy-variables
  environment: *deploy-lulu-caddy-environment

deploy-tag-lulu-caddy:
  extends: deploy-tag-lulu
  variables:
    <<: *deploy-caddy-variables
  environment: *deploy-lulu-caddy-environment
