services:
  tts-api:
    image: ${IMAGE_NAME:-pedroetb/tts-api}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME}
    environment:
      PORT:
    networks:
      tts-api-net:
    devices:
      - ${AUDIO_DEVICE:-/dev/snd}
    restart: always
    cpus: '${CPUS:-0.5}'
    mem_limit: ${MEM_LIMIT:-128M}
    mem_reservation: ${MEM_RESERVATION:-64M}

networks:
  tts-api-net:
    name: ${TTS_API_NET_NAME}
    driver: ${TTS_API_NET_DRIVER}
    external: true
